#ifndef DEV_QUEUE_CFG_H
#define DEV_QUEUE_CFG_H

#define DEV_QUEUE_CFG_RUNTIME_CHECK_ENABLED      (1U)
#define DEV_QUEUE_CFG_OVERWRITE_API_ENABLED      (1U)
#define DEV_QUEUE_CFG_PEEK_API_ENABLED           (1U)
#define DEV_QUEUE_CFG_MANY_API_ENABLED           (0U)
#define DEV_QUEUE_CFG_CLEAR_ON_RESET_ENABLED     (0U)
#define DEV_QUEUE_CFG_CRITICAL_SECTION_ENABLED   (0U)

#endif /* DEV_QUEUE_CFG_H */
